{"uuid": "e192528f-e055-481d-a287-1c7f14015864", "children": ["7d602e70-d6e6-4e7a-bb3c-ca794d33b83f"], "befores": [{"name": "create_token", "status": "broken", "statusDetails": {"message": "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='restful-booker.herokuapp.com', port=443): Max retries exceeded with url: /auth (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000233D8B78560>: Failed to resolve 'restful-booker.herokuapp.com' ([Errno 11001] getaddrinfo failed)\"))\n", "trace": "  File \"C:\\Users\\nitishjain8\\Py2xAPIAutomationFramework\\pythonProject\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 166, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\Users\\nitishjain8\\Py2xAPIAutomationFramework\\pythonProject\\venv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\nitishjain8\\Py2xAPIAutomationFramework\\pythonProject\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 102, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\nitishjain8\\Py2xAPIAutomationFramework\\pythonProject\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1132, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\nitishjain8\\Py2xAPIAutomationFramework\\pythonProject\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 913, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\nitishjain8\\Py2xAPIAutomationFramework\\pythonProject\\tests\\crud\\test_crud.py\", line 23, in create_token\n    response = post_request(url=APIConstants.url_create_token(),\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\nitishjain8\\Py2xAPIAutomationFramework\\pythonProject\\src\\helpers\\api_requests_wrapper.py\", line 12, in post_request\n    post_response = requests.post(url=url, headers=headers, auth=auth, data=json.dumps(payload))\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\nitishjain8\\Py2xAPIAutomationFramework\\pythonProject\\venv\\Lib\\site-packages\\requests\\api.py\", line 115, in post\n    return request(\"post\", url, data=data, json=json, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\nitishjain8\\Py2xAPIAutomationFramework\\pythonProject\\venv\\Lib\\site-packages\\requests\\api.py\", line 59, in request\n    return session.request(method=method, url=url, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\nitishjain8\\Py2xAPIAutomationFramework\\pythonProject\\venv\\Lib\\site-packages\\requests\\sessions.py\", line 589, in request\n    resp = self.send(prep, **send_kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\nitishjain8\\Py2xAPIAutomationFramework\\pythonProject\\venv\\Lib\\site-packages\\requests\\sessions.py\", line 703, in send\n    r = adapter.send(request, **kwargs)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\nitishjain8\\Py2xAPIAutomationFramework\\pythonProject\\venv\\Lib\\site-packages\\requests\\adapters.py\", line 519, in send\n    raise ConnectionError(e, request=request)\n"}, "start": 1712282579515, "stop": 1712282579529}], "start": 1712282579515, "stop": 1712282579886}